[INFO] mongodb.py:l.183 - Connected to MongoDB 10.0.10.10:27115, Server Informations :
[INFO] mongodb.py:l.185 - 	 version : 8.0.4
[INFO] mongodb.py:l.185 - 	 gitVersion : bc35ab4305d9920d9d0491c1c9ef9b72383d31f9
[INFO] mongodb.py:l.185 - 	 modules : []
[INFO] mongodb.py:l.185 - 	 allocator : tcmalloc-google
[INFO] mongodb.py:l.185 - 	 javascriptEngine : mozjs
[INFO] mongodb.py:l.185 - 	 sysInfo : deprecated
[INFO] mongodb.py:l.185 - 	 versionArray : [8, 0, 4, 0]
[INFO] mongodb.py:l.185 - 	 openssl : {'running': 'OpenSSL 3.0.13 30 Jan 2024', 'compiled': 'OpenSSL 3.0.13 30 Jan 2024'}
[INFO] mongodb.py:l.185 - 	 buildEnvironment : {'distmod': 'ubuntu2404', 'distarch': 'x86_64', 'cc': '/opt/mongodbtoolchain/v4/bin/gcc: gcc (GCC) 11.3.0', 'ccflags': '-Werror -include mongo/platform/basic.h -ffp-contract=off -fasynchronous-unwind-tables -g2 -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -gdwarf-5 -fno-omit-frame-pointer -fno-strict-aliasing -O2 -march=sandybridge -mtune=generic -mprefer-vector-width=128 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-unused-const-variable -Wno-unused-but-set-variable -Wno-missing-braces -Wno-psabi -fstack-protector-strong -gdwarf64 -Wa,--nocompress-debug-sections -fno-builtin-memcmp -Wimplicit-fallthrough=5', 'cxx': '/opt/mongodbtoolchain/v4/bin/g++: g++ (GCC) 11.3.0', 'cxxflags': '-Woverloaded-virtual -Wpessimizing-move -Wno-maybe-uninitialized -fsized-deallocation -std=c++20', 'linkflags': '-Wl,--fatal-warnings -B/opt/mongodbtoolchain/v4/bin -gdwarf-5 -pthread -Wl,-z,now -fuse-ld=lld -fstack-protector-strong -gdwarf64 -Wl,--build-id -Wl,--hash-style=gnu -Wl,-z,noexecstack -Wl,--warn-execstack -Wl,-z,relro -Wl,--compress-debug-sections=none -Wl,-z,origin -Wl,--enable-new-dtags', 'target_arch': 'x86_64', 'target_os': 'linux', 'cppdefines': 'SAFEINT_USE_INTRINSICS 0 PCRE2_STATIC ABSL_ALLOCATOR_NOTHROW NDEBUG _XOPEN_SOURCE 700 _GNU_SOURCE _FORTIFY_SOURCE 2 ABSL_FORCE_ALIGNED_ACCESS BOOST_ENABLE_ASSERT_DEBUG_HANDLER BOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF BOOST_LOG_NO_SHORTHAND_NAMES BOOST_LOG_USE_NATIVE_SYSLOG BOOST_LOG_WITHOUT_THREAD_ATTR BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS BOOST_SYSTEM_NO_DEPRECATED BOOST_THREAD_USES_DATETIME BOOST_THREAD_VERSION 5'}
[INFO] mongodb.py:l.185 - 	 bits : 64
[INFO] mongodb.py:l.185 - 	 debug : False
[INFO] mongodb.py:l.185 - 	 maxBsonObjectSize : 16777216
[INFO] mongodb.py:l.185 - 	 ok : 1.0
[INFO] mongodb.py:l.185 - 	 $clusterTime : {'clusterTime': Timestamp(1734678880, 56), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}
[INFO] mongodb.py:l.185 - 	 operationTime : Timestamp(1734678880, 56)
on 0: [INFO] mongodb.py:l.572 - Test global one by one sharding
on 100001: [INFO] mongodb.py:l.645 - Test global many sharding
on 100077: [INFO] mongodb.py:l.714 - Test one by one with various data sharding
on 104079: [INFO] mongodb.py:l.794 - Test many with various data sharding
on 108081: [ERROR] mongodb.py:l.216 - MongoDB.create_index : Index build failed: b56e962d-2c60-4549-9582-4d4c3a7f3201: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with 'unique' or 'prepareUnique' option over { id: 1 } with shard key pattern { _id: "hashed" }, full error: {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: b56e962d-2c60-4549-9582-4d4c3a7f3201: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: e8ec2f42-0b97-4bcb-9dc5-f38fda236a0c: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: b56e962d-2c60-4549-9582-4d4c3a7f3201: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680041, 1251), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680041, 1251)}
on 108081: [INFO] mongodb.py:l.572 - Test global one by one sharding
on 208082: [ERROR] mongodb.py:l.216 - MongoDB.create_index : Index build failed: 3a31e09e-9ee8-44d3-8bc9-4e7d29a62e54: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with 'unique' or 'prepareUnique' option over { id: 1 } with shard key pattern { _id: "hashed" }, full error: {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: 3a31e09e-9ee8-44d3-8bc9-4e7d29a62e54: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: 04ec7149-258c-49c9-8734-350cb77c1783: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: 3a31e09e-9ee8-44d3-8bc9-4e7d29a62e54: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680812, 7), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680812, 7)}
on 208082: [INFO] mongodb.py:l.645 - Test global many sharding_indexed
on 208158: [ERROR] mongodb.py:l.216 - MongoDB.create_index : Index build failed: 85c5d19c-e858-42eb-a04f-ee29bb6c43f7: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with 'unique' or 'prepareUnique' option over { id: 1 } with shard key pattern { _id: "hashed" }, full error: {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: 85c5d19c-e858-42eb-a04f-ee29bb6c43f7: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: 0be53d01-6ee5-4390-a3b1-85a6b59187a2: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: 85c5d19c-e858-42eb-a04f-ee29bb6c43f7: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680843, 6), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680843, 6)}
on 208158: [INFO] mongodb.py:l.714 - Test one by one with various data sharding_indexed
on 212160: [ERROR] mongodb.py:l.216 - MongoDB.create_index : Index build failed: 0e7d59de-b7e0-4eb2-9e11-d7c5992edccf: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with 'unique' or 'prepareUnique' option over { id: 1 } with shard key pattern { _id: "hashed" }, full error: {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: 0e7d59de-b7e0-4eb2-9e11-d7c5992edccf: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: 09012e28-fe7b-4208-87f2-45b65e4fb22e: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: 0e7d59de-b7e0-4eb2-9e11-d7c5992edccf: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680904, 216), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680904, 216)}
on 212160: [INFO] mongodb.py:l.794 - Test many with various data sharding_indexed
