on 108081: [ERROR] mongodb.py:l.96 - Operation failed : createIndexes - Query :  - Message : {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: b56e962d-2c60-4549-9582-4d4c3a7f3201: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: e8ec2f42-0b97-4bcb-9dc5-f38fda236a0c: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: b56e962d-2c60-4549-9582-4d4c3a7f3201: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680041, 1251), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680041, 1251)}
on 208082: [ERROR] mongodb.py:l.96 - Operation failed : createIndexes - Query :  - Message : {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: 3a31e09e-9ee8-44d3-8bc9-4e7d29a62e54: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: 04ec7149-258c-49c9-8734-350cb77c1783: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: 3a31e09e-9ee8-44d3-8bc9-4e7d29a62e54: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680812, 7), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680812, 7)}
on 208158: [ERROR] mongodb.py:l.96 - Operation failed : createIndexes - Query :  - Message : {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: 85c5d19c-e858-42eb-a04f-ee29bb6c43f7: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: 0be53d01-6ee5-4390-a3b1-85a6b59187a2: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: 85c5d19c-e858-42eb-a04f-ee29bb6c43f7: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680843, 6), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680843, 6)}
on 212160: [ERROR] mongodb.py:l.96 - Operation failed : createIndexes - Query :  - Message : {'raw': {'shard1_rs/10.0.10.11:27117,10.0.10.12:27118': {'ok': 0.0, 'errmsg': 'Index build failed: 0e7d59de-b7e0-4eb2-9e11-d7c5992edccf: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}, 'shard2_rs/10.0.10.21:27217,10.0.10.22:27218': {'ok': 0.0, 'errmsg': 'Index build failed: 09012e28-fe7b-4208-87f2-45b65e4fb22e: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', 'code': 67, 'codeName': 'CannotCreateIndex'}}, 'code': 67, 'codeName': 'CannotCreateIndex', 'ok': 0.0, 'errmsg': 'Index build failed: 0e7d59de-b7e0-4eb2-9e11-d7c5992edccf: Collection test.test ( 58a34f32-52f2-4120-a814-b7cbc9fa9b83 ) :: caused by :: cannot create index with \'unique\' or \'prepareUnique\' option over { id: 1 } with shard key pattern { _id: "hashed" }', '$clusterTime': {'clusterTime': Timestamp(1734680904, 216), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1734680904, 216)}
